#ifndef TOKEN_H
#define TOKEN_H

#include <bantam/TokenType.h>
#include <string>

namespace bantam
{

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
class Token final {
public:
	Token(TokenType type, const std::string& text)
		:mType(type),
		mText(text)
	{
	}

	TokenType getType() const { return mType; }
	std::string getText() const { return mText; }

	std::string toString() const { return mText; }

private:
	TokenType mType;
	std::string mText;
};

}

#endif
